### ISSUE TITLE
Workshop ui버그

### ISSUE THREAD

**Issue by malangbalam** [StonehearthForum/stoneHearth_locale_ko#1]
workshop의 오버레이 부분이 깨지는 오류

**Comment by oxchun** [comment]
Combat party Ui 깨지는 현상 (공격, 순찰, 방어 등 아이콘 안보임)

**Comment by malangbalam** [comment]
버그는 하나당 이슈 하나로 해주세요
구분하기 쉽게

**Comment by cred98** [comment]
해결 5d0a7e5f16c553b170058907792c341783a79076
