### ISSUE TITLE
.smod인식문제

### ISSUE THREAD

**Issue by malangbalam** [StonehearthForum/stoneHearth_locale_ko#10]
.smod는 zip파일 확장자를 바꾼 거뿐인데 인식이 안되는 문제가 있습니다. 해결방법을 궁리해봅시다.

**Comment by Goldmetal** [comment]
7z로 폴더를 추가해서 압축 할 때,
압축레벨을 '저장' (사실상 비압축)으로 맞추고 하면 정상적으로 작동합니다.
실제 테스트로 확인 완료.

**Comment by cred98** [comment]
그렇군요.  이슈 닫겠습니다.
