### ISSUE TITLE
클래스 Footman 용어 처리

### ISSUE THREAD

**Issue by goldmetal** [StonehearthForum/stoneHearth_locale_ko#2]
현재 Footman 을 전사로 표기하고 있지만
실질적인 의미로 보병이라는 것을 확인했습니다.
(사전적 의미는 '하인'이지만 성격이 다르므로 논외.)

**프로젝트 카드 : 
https://github.com/StonehearthForum/stoneHearth_locale_ko/projects/1#card-2425264**

전사 <-> 보병
의견이 확정되면 그쪽으로 업데이트 될 예정입니다.

**Comment by ghost** [comment]
번역본에 충실하게 하느냐 아니면 이해를 쉽게 현지화를 할 것이냐의 문제 같은데 요즘에 보병도 많이 쓰이는 표현이라서 보병으로 바뀌어도 문제 없을 꺼라고 생각합니다.
