### ISSUE TITLE
제 1차 용어통일

### ISSUE THREAD

**Issue by malangbalam** [StonehearthForum/stoneHearth_locale_ko#2]
용어의 통일을 위해 좋은 의견을 해주세요 :D

- stockpile: 아이템을 저장하는 공간
- workshop: 아이템을 제작할 수 있는 블럭들
- hearthling: 주민들을 부르는 명칭

**Comment by Goldmetal** [comment]
- stockpile : 비축 영역 (비축이란 뜻인데 인게임에 쓰이기엔 너무 어렵네요. )
- workshop : 작업대, 작업장
- hearthling : 정착민

**Comment by malangbalam** [comment]
stockpile은 저장고, 비축고 정도?
workshop은 작업대 좋네요

**Comment by Goldmetal** [comment]
'고' 는 건물 혹은 시설물을 의미하고 있어서,
영역으로만 지정하는 stockplie 과 조금 이질감이 있다고 생각합니다.
그래서 더욱 번역하기가 어려운 것 입니다.

**Comment by malangbalam** [comment]
비축소는 어떨까요

**Comment by Goldmetal** [comment]
소는 고보다 조금 더 근접한 느낌이네요.
괜찮을 것 같습니다.

**Comment by malangbalam** [comment]
그럼
비축소, 작업대, 정착민으로 통일하도록 하겠습니다.
