### ISSUE TITLE
Brench 혼동 우려에 대해

### ISSUE THREAD

**Issue by Goldmetal** [StonehearthForum/stoneHearth_locale_ko#3]
현재 stoneHearch_locale_ko - Alpha15 브렌치가

- malangbalam/stoneHearth_locale_ko
- StonehearthForum/stoneHearth_locale_ko

이렇게 두 개로 갈라져 있어서
혼동하기 쉽게 되어있는 상태입니다.

분명 StonehearthForum/stoneHearth_locale_ko를 받아서
작업하고 커밋했는데 malangbalam/stoneHearth_locale_ko에 반영이 되더라구요.

이슈는 StonehearthForum/stoneHearth_locale_ko 이쪽에서 계속 작성될거라
두 브렌치 사이를 왔다갔다 해야하는 불편함도 있습니다.

이러한 혼동과 불편함을 줄이기 위해 Merge가 필요할 것 같은데 어떤가요?

**Comment by malangbalam** [comment]
지워버리쵸 뭐
