### ISSUE TITLE
fork관련 문제

### ISSUE THREAD

**Issue by ghost** [StonehearthForum/stoneHearth_locale_ko#4]
현재 이 레포의 fork가 옥춘님 @oxchun 으로 되어있는데 추후 merge등을 위해서라도 stonehearth/startermod_locale 쪽으로 fork를 바꾸었으면 합니다만 문제는 이렇게 될 경우 현재 저장된 이슈,릴리즈,PR, 커밋메시지, project 가 다 날려버리고 하나의 커밋으로 병합해야하는데 어떻게 생각하시나요?

**Comment by goldmetal** [comment]
혹시 stoneHearth_locale_kr 레포 (stonehearthLocale 직속 fork)를 만들어주셨나요?
지금 조직 레포로 보니 새로 생겼네요.

저도 같은 문제로 골머리 앓고 있던 터라 차라리 다 날리는 한이 있어도
바꾸고 싶습니다.

문제는 기존 유저분들의 History를 날리는 건데
제가 결정해도 될지 그게 좀 마음에 걸리네요.
다 날려도 상관없다면 kr 쪽으로 옮기도록 하지요.

**Comment by ghost** [comment]
현재 레포를 legacy repo로 유지하고 직속 repo merge message에 마지막 commit을 남기는 식으로 작업했습니다. 추후 README에 '참여해주신 분들' 목록을 따로 적도록 하겠습니다.

현재 repo merge는 끝난 상태기 때문에 이슈 close하고 넘어가도록 하죠
