### ISSUE TITLE
Kingdom of [왕국이름] 해결방안

### ISSUE THREAD

**Issue by malangbalam** [StonehearthForum/stoneHearth_locale_ko#5]
메인화면에서 Kingdom of [마을이름]에 대한 해결책 중 어떤 게 나은 대안으로 생각하시는 지 알려주세요!

1. Kingdom of를 '왕국'으로 번역한 후 [마을이름] 뒤에 Kingdom of를 붙히고 위에 '최근 플레이한 게임: '을 추가한다.(지금 상태)
2. '왕국: '으로 바꾼다. (중국어, 일본어 번역모드에서 사용 중)
3. [마을이름]의 위치를 위로 올리고 오른쪽 아래에 '왕국'을 적는다. 폰트크기는 Kingdom of와 동일

예제)
1.
최근플레이한 게임:
### Example왕국

2.
왕국:
### Example

3.
### Example
왕국

**Comment by Goldmetal** [comment]
하이브리드로 "최근 플레이한 왕국 :" 을 기존처럼 위에 붙이고,
실제 왕국 이름만 중간에 둬도 괜찮을 것 같습니다.

**Comment by oxchun** [comment]
저도 골드메탈님과 같은 의견이에요

**Comment by malangbalam** [comment]
그럼 '최근 발전한 왕국'은 어떨까요

**Comment by Goldmetal** [comment]
플레이가 어떠냐에 따라서 발전일수도 있고 몰락할 수도 있는 부분이라 애매한 부분이 있네요..

**Comment by malangbalam** [comment]
발전을 운영으로 바꾸는 건?

**Comment by Goldmetal** [comment]
운영은 괜찮네요

**Comment by malangbalam** [comment]
그럼 그렇게 하는걸로 하죠

**Comment by malangbalam** [comment]
최근 운영한 왕국:
[마을이름]
