### ISSUE TITLE
Carpenters Workshop ui가 또 깨지는 문제

### ISSUE THREAD

**Issue by malangbalam** [StonehearthForum/stoneHearth_locale_ko#7]
필요조건란에 아이템 이미지가 노출 됨

**Comment by Goldmetal** [comment]
이 문제 정확히 어느 부분에서 이미지 노출이 되는지 알려주세요.
 (오른쪽 중앙 필요 아이템인지, 아래쪽 작업대,요구레벨 쪽인지..)

**Comment by cred98** [comment]
아래에 요구부분에요

**Comment by Goldmetal** [comment]
그쪽은 제가 걸어놓은 reference commit에서 한번 수정 했습니다.
혹시 시간되시면 수정된 것이 맞는지 확인해주세요.
맞다면 이 이슈 클로즈 하겠습니다.

**Comment by cred98** [comment]
아직이네요

**Comment by malangbalam** [comment]
![#](http://i.imgur.com/LCnpT84.jpg)

작업대/요구레벨 부분보시면 아이콘이 깨져있어여

**Comment by Goldmetal** [comment]
레시피 아이템 리스트가 밑으로 뚫고 나오는 문제였네요.
